import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast';

// These styles apply to every route in the application
import './globals.css'

export const metadata: Metadata = {
  title: 'DIP Buying Tool',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-700'>
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: "#374152",
              color: "#fff",
            },
            success: {
              style: {
                background: "#374152",
                border: "1px solid lightgreen",
              },
            },
            error: {
              style: {
                background: "#374152",
                border: "1px solid red",
              },
            },

            custom: {
              style: {
                background: "#374152",
                border: "1px solid lightgreen",
              },
            }
          }}
          reverseOrder={false}
        />
      </body>
    </html>
  )
}